# Generated by Django 2.2.4 on 2019-08-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
